# Generated by Django 3.0.6 on 2020-05-13 06:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumb_image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('author', models.CharField(default='admin', max_length=100)),
                ('selection1_image', models.ImageField(upload_to='')),
                ('selection1_des', models.CharField(max_length=20)),
                ('selection2_image', models.ImageField(upload_to='')),
                ('selection2_des', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selector', models.CharField(default='selecor', max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic')),
            ],
        ),
    ]
