# Generated by Django 3.0.6 on 2020-06-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postive_count', models.IntegerField(null=True)),
                ('negative_count', models.IntegerField(null=True)),
                ('postive_male_count', models.IntegerField(null=True)),
                ('postive_female_count', models.IntegerField(null=True)),
                ('negative_male_count', models.IntegerField(null=True)),
                ('negative_female_count', models.IntegerField(null=True)),
                ('postive_10age_count', models.IntegerField(null=True)),
                ('postive_10age_male_count', models.IntegerField(null=True)),
                ('postive_10age_female_count', models.IntegerField(null=True)),
                ('postive_20age_count', models.IntegerField(null=True)),
                ('postive_20age_male_count', models.IntegerField(null=True)),
                ('postive_20age_female_count', models.IntegerField(null=True)),
                ('postive_30age_count', models.IntegerField(null=True)),
                ('postive_30age_male_count', models.IntegerField(null=True)),
                ('postive_30age_female_count', models.IntegerField(null=True)),
                ('postive_40age_count', models.IntegerField(null=True)),
                ('postive_40age_male_count', models.IntegerField(null=True)),
                ('postive_40age_female_count', models.IntegerField(null=True)),
                ('postive_50age_count', models.IntegerField(null=True)),
                ('postive_50age_male_count', models.IntegerField(null=True)),
                ('postive_50age_female_count', models.IntegerField(null=True)),
                ('postive_60age_count', models.IntegerField(null=True)),
                ('postive_60age_male_count', models.IntegerField(null=True)),
                ('postive_60age_female_count', models.IntegerField(null=True)),
                ('negative_10age_count', models.IntegerField(null=True)),
                ('negative_10age_male_count', models.IntegerField(null=True)),
                ('negative_10age_female_count', models.IntegerField(null=True)),
                ('negative_20age_count', models.IntegerField(null=True)),
                ('negative_20age_male_count', models.IntegerField(null=True)),
                ('negative_20age_female_count', models.IntegerField(null=True)),
                ('negative_30age_count', models.IntegerField(null=True)),
                ('negative_30age_male_count', models.IntegerField(null=True)),
                ('negative_30age_female_count', models.IntegerField(null=True)),
                ('negative_40age_count', models.IntegerField(null=True)),
                ('negative_40age_male_count', models.IntegerField(null=True)),
                ('negative_40age_female_count', models.IntegerField(null=True)),
                ('negative_50age_count', models.IntegerField(null=True)),
                ('negative_50age_male_count', models.IntegerField(null=True)),
                ('negative_50age_female_count', models.IntegerField(null=True)),
                ('negative_60age_count', models.IntegerField(null=True)),
                ('negative_60age_male_count', models.IntegerField(null=True)),
                ('negative_60age_female_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic.Topic')),
            ],
        ),
    ]
