# Generated by Django 3.0.7 on 2020-07-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='selection_amount',
            field=models.IntegerField(default=0),
        ),
    ]
