# Generated by Django 3.0.6 on 2020-05-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='select',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
    ]
