# Generated by Django 3.0.6 on 2020-05-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection',
            old_name='age',
            new_name='age_range',
        ),
        migrations.RenameField(
            model_name='selection',
            old_name='sex',
            new_name='gender',
        ),
    ]
