# Generated by Django 3.0.6 on 2020-06-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
