# Generated by Django 3.0.6 on 2020-05-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20200524_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hot_topic',
            field=models.BooleanField(default=False),
        ),
    ]
