# Generated by Django 3.0.6 on 2020-05-25 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_topic_hot_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 1, 45, 3, 644064)),
        ),
    ]
