# Generated by Django 3.0.6 on 2020-06-06 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20200605_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
