# Generated by Django 3.0.7 on 2020-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20200716_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
