# Generated by Django 3.0.7 on 2020-06-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20200606_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_10age_count',
            new_name='positive_10age_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_10age_female_count',
            new_name='positive_10age_female_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_10age_male_count',
            new_name='positive_10age_male_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_20age_count',
            new_name='positive_20age_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_20age_female_count',
            new_name='positive_20age_female_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_20age_male_count',
            new_name='positive_20age_male_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_30age_count',
            new_name='positive_30age_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_30age_female_count',
            new_name='positive_30age_female_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_30age_male_count',
            new_name='positive_30age_male_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_40age_count',
            new_name='positive_40age_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_40age_female_count',
            new_name='positive_40age_female_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_40age_male_count',
            new_name='positive_40age_male_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_50age_count',
            new_name='positive_50age_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_50age_female_count',
            new_name='positive_50age_female_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_50age_male_count',
            new_name='positive_50age_male_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_60age_count',
            new_name='positive_60age_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_60age_female_count',
            new_name='positive_60age_female_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_60age_male_count',
            new_name='positive_60age_male_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_count',
            new_name='positive_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_female_count',
            new_name='positive_female_count',
        ),
        migrations.RenameField(
            model_name='dailydata',
            old_name='postive_male_count',
            new_name='positive_male_count',
        ),
    ]
