# Generated by Django 3.0.6 on 2020-05-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20200515_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='select',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
    ]
