# Generated by Django 3.0.7 on 2020-07-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20200722_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypick',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily', to='topic.Topic'),
        ),
    ]
