# Generated by Django 3.0.6 on 2020-07-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200604_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sido',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sigungu',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
